# Base configs
baseurl: "https://miaandcreations.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Polymer Creations by MIA"
subtitle: "Miniature polymer creations made to order"
author: "MIA"
header:
 title: "Polymer Creations"
 subtitle: "by MIA"
footer:
 name: "Hey there, I am MIA"
 bio: "I love making miniature polymer creations, contact me with your commission."
 github: ""
web_design: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
