# Base configs
baseurl: "https://miaandcreations.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Polymer Creations by MIA"
subtitle: "Miniature polymer creations"
author: "MIA"
header:
 title: "Polymer Creations"
 subtitle: "by MIA"
footer:
 name: "Hey there, I am MIA"
 bio: "Hello and welcome!
I was first introduced to polymer clay in 2021. It all started with making DIY gifts for family during the holidays. I slowly fell into the rabbit hole of YouTube and after many videos and multiple runs to Michael’s I found myself lost in the world of making small clay trinkets.

I am still learning and expanding my skills in polymer clay."
 github: ""
web_design: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
